apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: alloy-push-password
  namespace: rundeck
spec:
  encryptedData:
    password: AgCLwyXaYW67I3lflevXEuFQ/8VRJl7ebmfRMj0KdHctFr3SUmWExyU5LAzBYB9KXaGvMNZoryyHX4P9yqROYjidrqwXt058vvNa4kcIGlpj7z2kz5aF9w0WvXeoeKzPd7EH0+B7gKN9UQn/u9jnGblaNmE8hoFaKK3HQ7VoVO5VYtPSqL24fgfk5TSewMQZGxEsaL2KGXR/Cu+qMrXM8EXvRwWynFviF5rBgJx/pMl0hdseGftKx9f8BvnW86v1N/GEl4aQll3qxc9/yqmcuTLnZjEZEkP+bkw5cokMKFG2fFcTRcwgkb62t6t9NvzKf4ZmK5ofNpjnSqQ+MAqnMwyuv98KCbN4cYZSZHiWEsxoefrNiwFJz3uNbP31ytG3jBk/ZuiVDdoRH1dpO+CTbBZ5t3wiB4cpwfNF0cwiQEnDXF6np687I/1Yj1CtbEflmEBlrDHEhwLWUspNqQPvk8ByNmaRx1CFiMGUMgEnA1LapFUq9BilTC4PtyZfS66iRzGiSmakyAPNyvqoc8x7zsWALJzvI4aJWIPaTIwXggYPnC8yLudv5ffcgkWAnzfj4yJ5i7f9okewSv7jHKcn9TTiHrpcNVXEpDfGZBLN5GM6lPI1RlUEf9t4JcMIpX+umnbrDrDYPFsj4ToN3YGjVJEcdX5igmyCGTA7hV0AGFdTUrJpxwy1KITh+7oVdxzyXl9nG5zI5Ubw/krKQDcTMMWmc+r6mGg1Qcfl3Jv0I5O17PhU1YOmjLJEOw7bGPd2fwg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: alloy-push-password
      namespace: rundeck
    type: Opaque

