apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: alloy-push-password
  namespace: rundeck
spec:
  encryptedData:
    password: AgALckMO5TUtiZuhE0SESgRrwt+Df0/1rltS57O7EyFxQUQz70AYBCcK7rr8cRXo1XkEVRpQLsUCkWe92wCxCmh3h43hQ/+9xRjbpd968M86mvOpM6wA59ukw99QbpMzH1i1jqZWm8/JgEbml+w+aHipvlBsoZrSOh2ubbzOeAauRNlYQEfJ+KPC+yKAymtG+dtbV+itPpcuzlrdZ/VoqIolKaRno6iFvGvNWtFf0gs6HiPpueF7vxoQvf6EhfqXI+h3Ehaj5AnNyz5LqvxxKSeK/S9CfX0m4C8WpFQdO5F2TL/l0/1zLpSOGFt2o5i+QYq/t2t/9htVVfPOQKhqUHyib6EWIdMep680mO3o1qK7BFfHWoZYSXlYijPXQ96AnSKLKm+QCRMjPBtwG1QUeFbShgALbQp5vLdo9TJRJlFtOoh9x8FGh4VXIC3NhzHvKBi1xV1bzKLefE2Q1Hj19RghSmiifLYm2lq5pCq3NafOgOoipQFaeEU7SePvZhN++TbSsFF12KOqOzviyojN9tZNbN5XLDu9B3A01Qiuc6ptY3qUOpjEGhcYVMcerRZoCh/p27uAemwsd3s4eRrt0EHlBUIBeFWZdAO/XI6b7joJSt3rvEmZ1rO7rlB/UzRC9sUJJWPAiTRBM4r3k6BycHvd6DP4HRChYaPx9C02HIMxGnOpQfrzVjcIAhNsGgyznEyasR8Hanf9wJHLWqv1jrjs3/MwjffGNw67yKk3dKoVHmIJAW6hiaL15r+iqaR9UDo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: alloy-push-password
      namespace: rundeck
    type: Opaque

