apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mimir-push-auth
  namespace: mimir
spec:
  encryptedData:
    auth: AgCgxmNfmHupNiGwwlNQikh6g4CefvgufBzuN4wC2nGBywZAtCmF9DtsbuN9IgLWTWJrq7I5VfU8gZaIrdpA2R5QoZ3oFKwTh73qqBGZkibaFFge7lM0M+kxywyHqe+ldmqMa1GxD9G28ZGKXUnvNyaNB+vPYggBrbPMPF5si5OoVA76hTW2eEgo5DZsp9HPaNDrhHQsWNmGQ+iIPwStAaOAMjMluyAo6TyxlL8p2rEAQ4BCcsnWXUMPQAimqJFjay5YJ6nZvMNKK49AHQwK7M7YX8/6I2DVEXgaoeBCjU+PGJDp/HGohDJXKZGWGe3K9QGAnDNX3DZEuTREesYipFxamzCKUdE5JtKOGgT/f+bYAj0llV/1o1CrNK5LuX8paFvlOGOFNOPXH7cW9fTmNz8Obuba9YKlTHuA1xKC5bvOzOaESDr7So83XcYgOA2zO11C0ZGKptdjzBszwy9KhBf7hiRP6KAcW+2nSz9rdStsboXnG1oEJwQIinfItTJsyd6gcYQlN8LC/XEAGsZednQ9eBte0uIh93+q8KRNTsrg+ooTTNnUDdMHid178XkB6TPe/ksZHjYIy6SccVVX0sYvkA1fwEOB73Q4GIinE0f2QdCcsB+lAqpKkPAGNMcSiWH+Rw0p1p94AtiFv4PLUPDvdqigZ0BADhQDWjDrQ1uErO1yYqhYAU6KEfrKIUj0lcEATnY5SZKCtQCKKTU0p+qQ4XNU0JT/qQs0MUm3cQJrFpjpwcElBCmWhQ0YYBmuYTLzteLrUKSwtc/LN89+MUYKZJ8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mimir-push-auth
      namespace: mimir
    type: Opaque

